CREATE DATABASE portfolio;
USE portfolio;
CREATE TABLE Posts (
  PostID INT NOT NULL AUTO_INCREMENT,
  PostType VARCHAR(100) NOT NULL,
  Directory VARCHAR(100) NOT NULL,
  Postname VARCHAR(100) NOT NULL,
  Title VARCHAR(100) NOT NULL,
  PubDate DATE NOT NULL,
  Public BOOLEAN NOT NULL,
  Favoritism FLOAT NOT NULL,
  PRIMARY KEY (PostID)
);
CREATE TABLE PostSkills (
  PostID INT NOT NULL,
  Skill VARCHAR(100) NOT NULL,
  PRIMARY KEY (PostID, Skill),
  FOREIGN KEY (PostID) REFERENCES Posts(PostID)
);